### ISSUE TITLE
[BUG] Доска опционов

### ISSUE THREAD

**Issue by zlobinm** [alor-broker/Astras-Trading-UI#1811]
### Опишите баг

- не отображается дата исполнения. Например, по инструменту RTS-12.24 есть дата 26.09, в Доске опционов нет.
начинается только с 03.10
- Дополнить документацию: описание, информацию по полям
- Рядом с названием тикера после режима выводится **undefined**

### Воспроизведение

- Создать виджет. Примеры тикеров: RTS-12.24, NG-10.24

### Среда.

- ОС Windows
- Google Chrome, Microsoft Edge, Яндекс Браузер

### Ожидаемое поведение

- Если задумано не выводить дату исполнения, совпадающую с текущей, добавить пояснение в документацию
- Уточнить, что должно быть вместо **undefined**. Ожидаемо, что название тикера вида "RI100000BU4D"
- Если поле Цена имеет собственный расчет, добавить в документацию описание. В ином случае, поправить расчет для соответствия значению поля Теор. цена, в опционном калькуляторе биржи

### Дополнительная информация

Опционный калькулятор
https://www.moex.com/msn/ru-options-calc

### Правила

- [X] Я согласен следовать правилам

**Comment by zlobinm** [comment]
Добрый день

При выборе опциона - иконка цепи становится неактивной. 
При этом синхронизация с другими виджетами работает - если выбрать опцион, другие виджеты (например тех.анализ, стакан) покажут информацию по данному инструменту.

**Comment by YAV23** [comment]
Только доска опционов , потом не синхронизируется с виджетом "выбор инструментов", нужно опять цепочку нажать.

**Comment by independentimaginarium** [comment]
Добрый день. Виджет Доска опционов - тикер ТКСхолд (T) - выбрать вкладку Выбранные - по итогу зависает и не прогружаются данные. В консоли ошибка именно по ТКСхолд

```
General Error] object null is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at i.getOptionTranscription (https://astras.alor.ru/chunk-MKFCGO3Z.js:116:328013)
    at https://astras.alor.ru/chunk-MKFCGO3Z.js:116:326733
    at Array.map (<anonymous>)
    at https://astras.alor.ru/chunk-MKFCGO3Z.js:116:326623
    at https://astras.alor.ru/chunk-3AGZ56XB.js:3:19970
    at j0._next (https://astras.alor.ru/chunk-3AGZ56XB.js:3:5438)
    at j0.next (https://astras.alor.ru/chunk-3AGZ56XB.js:3:2523)
    at https://astras.alor.ru/chunk-3AGZ56XB.js:3:19963
    at j0._next (https://astras.alor.ru/chunk-3AGZ56XB.js:3:5438)
```

оформить в отдельный баг?
